server:
  port: 8081
  
spring:
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    url: jdbc:sqlite:nps.db
    username: 
    password: 
    driver-class-name: org.sqlite.JDBC
    
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.finastra: DEBUG

auth:
  keyId: <%keyID%>
  strong: false
  
finastra:
    oauth2:
      client:
        grant-type: client_credentials
        clientId: 257b9c3d-105c-49b0-a079-fe83e35450b5
        clientSecret: 45398b49-64c9-46bb-9211-8655e2d5750f
        accessTokenUri: ${ffdcapi.loginUrl}/sandbox/oidc/token
        userAuthorizationUri: ${ffdcapi.loginUrl}/sandbox/oidc/authorize
        scope: openid

ffdcapi:
  baseUrl: https://api.fusionfabric.cloud
  loginUrl: ${ffdcapi.baseUrl}/login/v1
  
oauth2.callbackPath: /login/oauth2/code/finastra
oauth2.jwkSetUri: ${ffdcapi.loginUrl}/oidc/jwks.json